DROP TABLE fact_commandes;
CREATE TABLE fact_commandes (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
    commande_id VARCHAR2(100),
    chiffre_affaire NUMBER,
    id_produit NUMBER,
    id_date NUMBER,
    id_lieu NUMBER,
    id_avis NUMBER,
    CONSTRAINT fact_pk PRIMARY KEY (id),
    CONSTRAINT fact_produit_fk FOREIGN KEY (id_produit) REFERENCES dim_produits(id),
    CONSTRAINT fact_date_fk FOREIGN KEY (id_date) REFERENCES dim_dates(id),
    CONSTRAINT fact_lieu_fk FOREIGN KEY (id_lieu) REFERENCES dim_lieux(id),
    CONSTRAINT fact_avis_fk FOREIGN KEY (id_avis) REFERENCES dim_avis(id)
);

INSERT INTO 
    fact_commandes(
        commande_id, 
        chiffre_affaire, 
        id_produit, 
        id_date, 
        id_lieu, 
        id_avis
    )
SELECT 
    c.getId(), 
    c.getQuantite()*c.getPrix(), 
    dp.id, dd.id, dl.id, da.id
FROM 
    commandes c, dim_produits dp, dim_avis da, dim_dates dd, dim_lieux dl
WHERE 
    c.getProduit() = dp.produit_id 
    AND c.getAvis() = da.avis_id 
    AND c.getDate() = dd.date_id AND c.getLivraisonJours() = dd.livraison_days
    AND c.getLieu() = dl.code_postal;

COMMIT;